// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: etcdserverpb.kv.proto

module etcdserverpb.kv;

import google.protobuf;

enum protocVersion = 3006001;

class KeyValue
{
    @Proto(1) bytes key = protoDefaultValue!bytes;
    @Proto(2) long createRevision = protoDefaultValue!long;
    @Proto(3) long modRevision = protoDefaultValue!long;
    @Proto(4) long version_ = protoDefaultValue!long;
    @Proto(5) bytes value = protoDefaultValue!bytes;
    @Proto(6) long lease = protoDefaultValue!long;
}

class Event
{
    @Proto(1) EventType type = protoDefaultValue!EventType;
    @Proto(2) KeyValue kv = protoDefaultValue!KeyValue;
    @Proto(3) KeyValue prevKv = protoDefaultValue!KeyValue;

    enum EventType
    {
        PUT = 0,
        DELETE = 1,
    }
}
