module neton.protocol.netonrpc;


// Generated by the gRPC dlang plugin.


import neton.protocol.neton;
import std.array;
import grpc;
import google.protobuf;
import hunt.logging;
import core.thread;




class KVClient
{
	this(Channel channel)
	{
		_channel = channel;
	}

	RangeResponse Range( RangeRequest request)
	{
		mixin(CM!(RangeResponse , KVBase.SERVICE));
	}

	void Range( RangeRequest request , void delegate(Status status , RangeResponse response) dele)
	{
		mixin(CMA!(RangeResponse , KVBase.SERVICE));
	}

	PutResponse Put( PutRequest request)
	{
		mixin(CM!(PutResponse , KVBase.SERVICE));
	}

	void Put( PutRequest request , void delegate(Status status , PutResponse response) dele)
	{
		mixin(CMA!(PutResponse , KVBase.SERVICE));
	}

	DeleteRangeResponse DeleteRange( DeleteRangeRequest request)
	{
		mixin(CM!(DeleteRangeResponse , KVBase.SERVICE));
	}

	void DeleteRange( DeleteRangeRequest request , void delegate(Status status , DeleteRangeResponse response) dele)
	{
		mixin(CMA!(DeleteRangeResponse , KVBase.SERVICE));
	}


	private:
	Channel _channel;
}

class KVBase: GrpcService
{
	enum SERVICE  = "neton.protocol.KV";
	string getModule()
	{
		return SERVICE;
	}

	Status Range(RangeRequest , ref RangeResponse){ return Status.OK; }
	Status Put(PutRequest , ref PutResponse){ return Status.OK; }
	Status DeleteRange(DeleteRangeRequest , ref DeleteRangeResponse){ return Status.OK; }

	Status process(string method , GrpcStream stream)
	{
		switch(method)
		{
			mixin(SM!(RangeRequest , RangeResponse , "Range"));
			mixin(SM!(PutRequest , PutResponse , "Put"));
			mixin(SM!(DeleteRangeRequest , DeleteRangeResponse , "DeleteRange"));
			mixin(NONE());
		}
	}
}


class ConfigClient
{
	this(Channel channel)
	{
		_channel = channel;
	}

	RangeResponse Range( RangeRequest request)
	{
		mixin(CM!(RangeResponse , ConfigBase.SERVICE));
	}

	void Range( RangeRequest request , void delegate(Status status , RangeResponse response) dele)
	{
		mixin(CMA!(RangeResponse , ConfigBase.SERVICE));
	}

	PutResponse Put( PutRequest request)
	{
		mixin(CM!(PutResponse , ConfigBase.SERVICE));
	}

	void Put( PutRequest request , void delegate(Status status , PutResponse response) dele)
	{
		mixin(CMA!(PutResponse , ConfigBase.SERVICE));
	}

	DeleteRangeResponse DeleteRange( DeleteRangeRequest request)
	{
		mixin(CM!(DeleteRangeResponse , ConfigBase.SERVICE));
	}

	void DeleteRange( DeleteRangeRequest request , void delegate(Status status , DeleteRangeResponse response) dele)
	{
		mixin(CMA!(DeleteRangeResponse , ConfigBase.SERVICE));
	}


	private:
	Channel _channel;
}

class ConfigBase: GrpcService
{
	enum SERVICE  = "neton.protocol.Config";
	string getModule()
	{
		return SERVICE;
	}

	Status Range(RangeRequest , ref RangeResponse){ return Status.OK; }
	Status Put(PutRequest , ref PutResponse){ return Status.OK; }
	Status DeleteRange(DeleteRangeRequest , ref DeleteRangeResponse){ return Status.OK; }

	Status process(string method , GrpcStream stream)
	{
		switch(method)
		{
			mixin(SM!(RangeRequest , RangeResponse , "Range"));
			mixin(SM!(PutRequest , PutResponse , "Put"));
			mixin(SM!(DeleteRangeRequest , DeleteRangeResponse , "DeleteRange"));
			mixin(NONE());
		}
	}
}


class RegistryClient
{
	this(Channel channel)
	{
		_channel = channel;
	}

	RangeResponse Range( RangeRequest request)
	{
		mixin(CM!(RangeResponse , RegistryBase.SERVICE));
	}

	void Range( RangeRequest request , void delegate(Status status , RangeResponse response) dele)
	{
		mixin(CMA!(RangeResponse , RegistryBase.SERVICE));
	}

	PutResponse Put( PutRequest request)
	{
		mixin(CM!(PutResponse , RegistryBase.SERVICE));
	}

	void Put( PutRequest request , void delegate(Status status , PutResponse response) dele)
	{
		mixin(CMA!(PutResponse , RegistryBase.SERVICE));
	}

	DeleteRangeResponse DeleteRange( DeleteRangeRequest request)
	{
		mixin(CM!(DeleteRangeResponse , RegistryBase.SERVICE));
	}

	void DeleteRange( DeleteRangeRequest request , void delegate(Status status , DeleteRangeResponse response) dele)
	{
		mixin(CMA!(DeleteRangeResponse , RegistryBase.SERVICE));
	}


	private:
	Channel _channel;
}

class RegistryBase: GrpcService
{
	enum SERVICE  = "neton.protocol.Registry";
	string getModule()
	{
		return SERVICE;
	}

	Status Range(RangeRequest , ref RangeResponse){ return Status.OK; }
	Status Put(PutRequest , ref PutResponse){ return Status.OK; }
	Status DeleteRange(DeleteRangeRequest , ref DeleteRangeResponse){ return Status.OK; }

	Status process(string method , GrpcStream stream)
	{
		switch(method)
		{
			mixin(SM!(RangeRequest , RangeResponse , "Range"));
			mixin(SM!(PutRequest , PutResponse , "Put"));
			mixin(SM!(DeleteRangeRequest , DeleteRangeResponse , "DeleteRange"));
			mixin(NONE());
		}
	}
}


class WatchClient
{
	this(Channel channel)
	{
		_channel = channel;
	}

	ClientReaderWriter!(WatchResponse ,WatchRequest) Watch(){
		mixin(CM3!(WatchResponse , WatchRequest  , WatchBase.SERVICE));
	}

	private:
	Channel _channel;
}

class WatchBase: GrpcService
{
	enum SERVICE  = "neton.protocol.Watch";
	string getModule()
	{
		return SERVICE;
	}

	Status Watch(ServerReaderWriter!(WatchRequest , WatchResponse)){ return Status.OK; }

	Status process(string method , GrpcStream stream)
	{
		switch(method)
		{
			mixin(SM3!(WatchRequest , WatchResponse , "Watch"));
			mixin(NONE());
		}
	}
}


class LeaseClient
{
	this(Channel channel)
	{
		_channel = channel;
	}

	LeaseGrantResponse LeaseGrant( LeaseGrantRequest request)
	{
		mixin(CM!(LeaseGrantResponse , LeaseBase.SERVICE));
	}

	void LeaseGrant( LeaseGrantRequest request , void delegate(Status status , LeaseGrantResponse response) dele)
	{
		mixin(CMA!(LeaseGrantResponse , LeaseBase.SERVICE));
	}

	LeaseRevokeResponse LeaseRevoke( LeaseRevokeRequest request)
	{
		mixin(CM!(LeaseRevokeResponse , LeaseBase.SERVICE));
	}

	void LeaseRevoke( LeaseRevokeRequest request , void delegate(Status status , LeaseRevokeResponse response) dele)
	{
		mixin(CMA!(LeaseRevokeResponse , LeaseBase.SERVICE));
	}

	ClientReaderWriter!(LeaseKeepAliveResponse ,LeaseKeepAliveRequest) LeaseKeepAlive(){
		mixin(CM3!(LeaseKeepAliveResponse , LeaseKeepAliveRequest  , LeaseBase.SERVICE));
	}
	LeaseTimeToLiveResponse LeaseTimeToLive( LeaseTimeToLiveRequest request)
	{
		mixin(CM!(LeaseTimeToLiveResponse , LeaseBase.SERVICE));
	}

	void LeaseTimeToLive( LeaseTimeToLiveRequest request , void delegate(Status status , LeaseTimeToLiveResponse response) dele)
	{
		mixin(CMA!(LeaseTimeToLiveResponse , LeaseBase.SERVICE));
	}

	LeaseLeasesResponse LeaseLeases( LeaseLeasesRequest request)
	{
		mixin(CM!(LeaseLeasesResponse , LeaseBase.SERVICE));
	}

	void LeaseLeases( LeaseLeasesRequest request , void delegate(Status status , LeaseLeasesResponse response) dele)
	{
		mixin(CMA!(LeaseLeasesResponse , LeaseBase.SERVICE));
	}


	private:
	Channel _channel;
}

class LeaseBase: GrpcService
{
	enum SERVICE  = "neton.protocol.Lease";
	string getModule()
	{
		return SERVICE;
	}

	Status LeaseGrant(LeaseGrantRequest , ref LeaseGrantResponse){ return Status.OK; }
	Status LeaseRevoke(LeaseRevokeRequest , ref LeaseRevokeResponse){ return Status.OK; }
	Status LeaseKeepAlive(ServerReaderWriter!(LeaseKeepAliveRequest , LeaseKeepAliveResponse)){ return Status.OK; }
	Status LeaseTimeToLive(LeaseTimeToLiveRequest , ref LeaseTimeToLiveResponse){ return Status.OK; }
	Status LeaseLeases(LeaseLeasesRequest , ref LeaseLeasesResponse){ return Status.OK; }

	Status process(string method , GrpcStream stream)
	{
		switch(method)
		{
			mixin(SM!(LeaseGrantRequest , LeaseGrantResponse , "LeaseGrant"));
			mixin(SM!(LeaseRevokeRequest , LeaseRevokeResponse , "LeaseRevoke"));
			mixin(SM3!(LeaseKeepAliveRequest , LeaseKeepAliveResponse , "LeaseKeepAlive"));
			mixin(SM!(LeaseTimeToLiveRequest , LeaseTimeToLiveResponse , "LeaseTimeToLive"));
			mixin(SM!(LeaseLeasesRequest , LeaseLeasesResponse , "LeaseLeases"));
			mixin(NONE());
		}
	}
}


class ClusterClient
{
	this(Channel channel)
	{
		_channel = channel;
	}

	MemberAddResponse MemberAdd( MemberAddRequest request)
	{
		mixin(CM!(MemberAddResponse , ClusterBase.SERVICE));
	}

	void MemberAdd( MemberAddRequest request , void delegate(Status status , MemberAddResponse response) dele)
	{
		mixin(CMA!(MemberAddResponse , ClusterBase.SERVICE));
	}

	MemberRemoveResponse MemberRemove( MemberRemoveRequest request)
	{
		mixin(CM!(MemberRemoveResponse , ClusterBase.SERVICE));
	}

	void MemberRemove( MemberRemoveRequest request , void delegate(Status status , MemberRemoveResponse response) dele)
	{
		mixin(CMA!(MemberRemoveResponse , ClusterBase.SERVICE));
	}

	MemberUpdateResponse MemberUpdate( MemberUpdateRequest request)
	{
		mixin(CM!(MemberUpdateResponse , ClusterBase.SERVICE));
	}

	void MemberUpdate( MemberUpdateRequest request , void delegate(Status status , MemberUpdateResponse response) dele)
	{
		mixin(CMA!(MemberUpdateResponse , ClusterBase.SERVICE));
	}

	MemberListResponse MemberList( MemberListRequest request)
	{
		mixin(CM!(MemberListResponse , ClusterBase.SERVICE));
	}

	void MemberList( MemberListRequest request , void delegate(Status status , MemberListResponse response) dele)
	{
		mixin(CMA!(MemberListResponse , ClusterBase.SERVICE));
	}


	private:
	Channel _channel;
}

class ClusterBase: GrpcService
{
	enum SERVICE  = "neton.protocol.Cluster";
	string getModule()
	{
		return SERVICE;
	}

	Status MemberAdd(MemberAddRequest , ref MemberAddResponse){ return Status.OK; }
	Status MemberRemove(MemberRemoveRequest , ref MemberRemoveResponse){ return Status.OK; }
	Status MemberUpdate(MemberUpdateRequest , ref MemberUpdateResponse){ return Status.OK; }
	Status MemberList(MemberListRequest , ref MemberListResponse){ return Status.OK; }

	Status process(string method , GrpcStream stream)
	{
		switch(method)
		{
			mixin(SM!(MemberAddRequest , MemberAddResponse , "MemberAdd"));
			mixin(SM!(MemberRemoveRequest , MemberRemoveResponse , "MemberRemove"));
			mixin(SM!(MemberUpdateRequest , MemberUpdateResponse , "MemberUpdate"));
			mixin(SM!(MemberListRequest , MemberListResponse , "MemberList"));
			mixin(NONE());
		}
	}
}


